---
apiVersion: v1
kind: ReplicationController
metadata:
  name: p9-demo-ui
spec:
  replicas: 3
  selector:
    app: p9-demo-ui
  template:
    metadata:
      name: p9-demo-ui
      labels:
        app: p9-demo-ui
    spec:
      containers:
      - name: mongodb
        image: quay.io/jmarhee/p9-demo-ui
        ports:
        - containerPort: 4567

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: p9-demo-ui
# spec:
#   ports:
#     - port: 8080
#       targetPort: 4567
#   selector:
#     app: p9-demo-ui

kind: Service
apiVersion: v1
metadata:
  name: p9-demo-ui
spec:
  selector:
    app: p9-demo-ui 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4567
    nodePort: 30061
  type: LoadBalancer

#p9-demo-ui.p9-demo.svc.cluster.local
