---
apiVersion: v1
kind: ReplicationController
metadata:
  name: p9-demo-mongo
spec:
  replicas: 1
  selector:
    app: p9-demo-mongo
  template:
    metadata:
      name: p9-demo-mongo
      labels:
        app: p9-demo-mongo
    spec:
      containers:
      - name: mongodb
        image: quay.io/jmarhee/p9-demo-mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: p9-demo-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: p9-demo-mongo

#p9-demo-mongo.p9-demo.svc.cluster.local
