---
apiVersion: v1
kind: ReplicationController
metadata:
  name: p9-demo-ui
  namespace: p9-demo
spec:
  replicas: 3
  selector:
    app: p9-demo-ui
  template:
    metadata:
      name: p9-demo-ui
      labels:
        app: p9-demo-ui
    spec:
      containers:
      - name: demo-ui
        image: quay.io/jmarhee/p9-demo-ui
        ports:
        - containerPort: 4567

---
kind: Service
apiVersion: v1
metadata:
  name: p9-demo-ui
  namespace: p9-demo
spec:
  selector:
    app: p9-demo-ui 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4567
    nodePort: 30061
  type: LoadBalancer

#p9-demo-ui.p9-demo.svc.cluster.local
